### ISSUE TITLE
Licensing slip-up

### ISSUE THREAD

**Issue by Fireflies** [CodeLanx/CodelanxLib#13]
![License graphic](https://camo.githubusercontent.com/3371064e22c03e77178b760c4b15998a577ebc8e/687474703a2f2f692e696d6775722e636f6d2f574d777a6845612e706e67)

The license graphic provided in the README says commercial usage is permitted, however the file header says you are using a non commercial variant of the license. :stuck_out_tongue_winking_eye:

**Comment by 1Rogue** [comment]
In terms of creative commons, it's (typically) a self-describing aspect of the license, in that the software is non-commercial. The graphic in this specific case will always be the more accurate ruling to go by, as a custom license hasn't been fully written for many projects.
